version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: messenger_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: messenger_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: messenger_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth:
    build: ./services/auth
    container_name: messenger_auth
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/messenger
      REDIS_HOST: redis
    ports:
      - "3001:3000"
    volumes:
      - ./services/auth:/app
      - /app/node_modules

volumes:
  pgdata:
