services:
  postgres:
    image: postgres:15
    container_name: messenger_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: messenger_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: messenger_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  gateway:
    build: ./gateway
    container_name: messenger_gateway
    restart: always
    depends_on:
      - auth
    env_file:
      - ./gateway/.env
    environment:
      AUTH_SERVICE_URL: auth:50051
      REDIS_HOST: redis
      JWT_SECRET: your-secret
    ports:
      - "3000:3000"  # или любой внешний порт

  auth:
    build: ./services/auth
    container_name: messenger_auth
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: messenger
      REDIS_HOST: redis
      JWT_SECRET: your-secret
#    volumes:
#      - ./services/auth:/app
#      - /app/node_modules
    # ports:
    #   - "50051:50051" # если хочешь gRPC наружу

volumes:
  pgdata:
